#!/usr/bin/python
import sys,os

def parse_args(args):
	import argparse
	p = argparse.ArgumentParser(description="Build and compile any program with pymake")
    # p.add_argument()
    return parser.parse_args(args)

if __name__ == '__main__':
	parse_args(sys.argv)